version: '2'

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      redis-network:
          aliases:
            - redis
    hostname: redis
    volumes:
      - ./redis-data/redis/data:/bitnami/redis/data
      - ./redis-data/redis/conf:/bitnami/redis/conf
    ports:
      - '6379:6379'
  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '6380:6379'
    depends_on:
      - redis
    networks:
      redis-network:
          aliases:
            - redis-slave
    hostname: redis-slave
    volumes:
      - ./redis-data/redis-slave/data:/bitnami/redis/data
      - ./redis-data/redis-slave/conf:/bitnami/redis/conf

  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SENTINEL_PASSWORD=${REDIS_PASSWORD}     
      - REDIS_SENTINEL_QUORUM=1 
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26379:26379'
    networks:
      redis-network:
          aliases:
            - redis-sentinel
    hostname: redis-sentinel

  redis-sentinel2:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SENTINEL_PASSWORD=${REDIS_PASSWORD}     
      - REDIS_SENTINEL_QUORUM=1 
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26380:26379'
    networks:
      redis-network:
          aliases:
            - redis-sentinel2
    hostname: redis-sentinel2

  redis-sentinel3:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_SENTINEL_PASSWORD=${REDIS_PASSWORD}     
      - REDIS_SENTINEL_QUORUM=1 
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26381:26379'
    networks:
      redis-network:
          aliases:
            - redis-sentinel3
    hostname: redis-sentinel3
  
  # this is just for testing (if you have redis-cli installed this is not required)
  console:
    build: 
      context: ./console
      dockerfile: Dockerfile.console    
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      redis-network:
          aliases:
            - console
    hostname: console    

networks:
  redis-network:
    name: redis-network