FROM python:3.9-slim-bullseye

LABEL  "MAINTAINER" "Enrique Catalá Bañuls <enrique@enriquecatala.com>"
LABEL "Project" "Redis"
LABEL project="Redis" role="Backend" sku="cpu"


# install redis client
RUN apt-get update && apt-get install -y bc dnsutils redis-tools vim iputils-ping telnet

# prepare python 
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt


COPY testsentinel.py testsentinel.py

# Entrypoint overrided
ENTRYPOINT ["sleep", "infinity"]